### ISSUE TITLE
[Feature Request] Option to disallow user library creation

### ISSUE THREAD

**Issue by Sightem** [Dusk-Labs/dim#435] opened 2022-05-02 19:08 UTC
**Is your feature request related to a problem? Please describe.**
The administrator account should be able to disallow normal users from creating new libraries

**Describe the solution you'd like**
Per user permission toggle

**Describe alternatives you've considered**
The addition of different user groups with different levels of permissions could also achieve this, perhaps in a better way even

**Additional context**
None

**Comment by vgarleanu** [comment] 2023-04-02 22:53
Closing as duplicate of #330

**Closed by vgarleanu** 2023-04-02 22:53 UTC
Labels: T-feature-request, S-needs-triage
