### ISSUE TITLE
Remove build dependency on nightly

### ISSUE THREAD

**Issue by AndreasDavour** [Dusk-Labs/dim#426] opened 2022-04-08 07:44 UTC
**Is your feature request related to a problem? Please describe.**
Running on "nightly" is basically a build dependency on beta level software. It's a very controlled beta, but still.

**Describe the solution you'd like**
I'd like to have a mature software stack that does not depend on "the new hotness" but in solid stable, supported and tested features.

**Describe alternatives you've considered**
I'd suggest a plan and an ETA for when the build dependency on nightly can be removed and be fully dependent on the stable rustc.

**Additional context**

**Comment by cobyge** [comment] 2022-04-23 20:21
Hi,
I attempted to build Dim from scratch (Using cargo build --release) on the workspace, and it managed to compile successfully.  
This was using stable `rustc 1.60.0`.  
I couldn't find anything that depends on nightly in the repository.  Is this still relevant?

**Comment by vgarleanu** [comment] 2022-04-23 20:22
Dim doesn't depend on nightly anymore, the README is just out-of-date. Closing as the issue is fixed.

**Closed by vgarleanu** 2022-04-23 20:22 UTC
Labels: T-feature-request, S-needs-triage
